
//nos permite hacer las peticiones

# GET http://localhost:3000/taxis

# GET http://localhost:3000/taxi?taxi_id=1

# GET http://localhost:3000/taxi?plate=KFEO-6656

http://localhost:3000/trajectories/all?page=2&limit=10

# GET http://localhost:3000/trajectories?taxi_id=10133&page=2&limit=10


# GET http://localhost:3000/trajectories?page=1000&limit=10

# GET http://localhost:3000/trajectories/latest?page=1&limit=10

# POST http://localhost:3000/trajectories/report
# Content-Type: application/json

# {
#   "taxi_id": "10133",
#   "date": "2008-02-04",
#   "email":"educ.dana@gmail.com"
# }

# GET http://localhost:3000/lasttrajectory?taxi_id=7956



//-------------------------ERRORES-----------------------------

//ERROR con 2 paremetros
# GET http://localhost:3000/trajectories?taxi_id=10133&date=2008-02-04&page=20

//ERROR no hay datos que mostrar
# GET http://localhost:3000/trajectories?date=2008-02-04&page=900
# GET http://localhost:3000/trajectories?date=2028-02-04&page=1&limit=10

//ERROR no hay parametros 
# GET http://localhost:3000/trajectories?date=

//ERROR date no es valido(Aun no codeado)
# GET http://localhost:3000/trajectories?page=ffff

//EROR no hay paremtros insertados
# GET http://localhost:3000/trajectories


# http://localhost:3000/excel


