
//nos permite hacer las peticiones

# GET http://localhost:3000/taxis

GET http://localhost:3000/taxis?plate=CGEF-7101

# GET http://localhost:3000/trajectories

# GET http://localhost:3000/trajectories?taxi_id=8935&date=2008-02-04

# GET http://localhost:3000/trajectories?date=&page=1&limit=10

# GET http://localhost:3000/trajectories?taxi_id=8935


# GET http://localhost:3000/lasttrajectorie?taxi_id=10133

# GET http://localhost:3000/trajectories/latest


# 
# Content-Type: application/json
# {
    
# }
